### ISSUE TITLE
Cannot access the preferences when more than 9 workspaces are manually named

### ISSUE THREAD

**Issue by Dinduks** [dyson/indicator-workspaces#2]
Hi,

When I use `gsettings set org.gnome.desktop.wm.preferences workspace-names` to name more than 9 workspaces (e.g. with the `"['1','2','3','4','5','6','7','8','9','10','11','12']"` argument), trying to access the preferences triggers this error:

```
Traceback (most recent call last):
  File "./indicator-workspaces", line 67, in create_workspace_preferences
    self.workspaces_preferences
AttributeError: 'IndicatorWorkspaces' object has no attribute 'workspaces_preferences'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./indicator-workspaces", line 69, in create_workspace_preferences
    self.workspaces_preferences = WorkspacesPreferences(self)
  File "./indicator-workspaces", line 186, in __init__
    self.entry_workspaces[index].set_text(workspace_name)
IndexError: list index out of range
```

Thank you.

Samy

**Comment by dyson** [comment]
Thanks for the report! Easy fix but I am on holiday with limited internet for another week!

Pull request welcome otherwise I'll fix it when I'm back.

Thanks again!

**Comment by Dinduks** [comment]
As far as I understand, the error occurs because no `entry-workspace-N`, where `N > 9`, is defined in the _indicator-workspaces-preferences.glade_ file.  
Since you say it's easy to fix, I'll let you do it because I don't wanna break anything! :smile: 

Thank you!
